name: 'Test SDK'
description: 'Unit and Universal Tests'
inputs:
  test_data_branch:
    type: string
    description: The branch in sdk-test-data to target for testcase files
    required: false
    default: main
  sdk_branch:
    type: string
    description: The branch of the SDK to test
    required: false
    default: main

runs:
  using: composite
  steps:
    - name: Display Testing Details
      shell: bash
      run: |
        echo "Running SDK Test using"
        echo "Test Data: sdk-test-data@${TEST_DATA_BRANCH_NAME}"
        echo "SDK Branch: python-sdk@${SDK_BRANCH_NAME}"
      env:
        SDK_BRANCH_NAME: ${{ inputs.sdk_branch }}
        TEST_DATA_BRANCH_NAME: ${{ inputs.test_data_branch }}

    - uses: "actions/checkout@v2"
      with:
        repository: Eppo-exp/python-sdk
        ref: ${{ inputs.sdk_branch }}
    - uses: "actions/setup-python@v2"
      with:
        python-version: '3.9.x'
    - name: "Install dependencies"
      shell: bash
      run: |
        python -VV
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-test.txt
    - name: "Run tests"
      shell: bash
      run: make test branchName=$BRANCH
      env:
        BRANCH: ${{ inputs.test_data_branch }}
